name: Build-Development

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  Build:
    # To build `net45` target, we need to run the build on Windows.
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    # Build
    - run: dotnet restore
    - run: dotnet build -c Release

    # Run Unit tests
    #- run: dotnet test -c Release --no-build --logger trx --results-directory $GITHUB_WORKSPACE/artifacts

    # Packaging
    - name: dotnet pack Kurukuru
      run: dotnet pack -c Release --no-build -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output $GITHUB_WORKSPACE/artifacts ./Kurukuru/Kurukuru.csproj

    # Upload & Publish
    - uses: actions/upload-artifact@master
      with:
        name: Packages
        path: artifacts