name: Build-Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    if: "contains(github.ref, 'refs/tags')"

    # To build `net45` target, we need to run the build on Windows.
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    
    steps:
    - uses: actions/checkout@v1
    
    # Load secrets from 1Password
    - uses: 1password/load-secrets-action@v2
      id: op-load-secret
      with:
        export-env: false
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_PUBLIC }}
        NUGET_AUTH_TOKEN: "op://GitHub Actions - Public/NuGet - Mayuki-Default/credential"
        
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: "dotnet build & pack"
      run: |
        dotnet restore
        dotnet build -c Release
        dotnet pack -c Release -o ./artifacts -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

    - uses: actions/upload-artifact@master
      with:
        name: Packages
        path: artifacts

    - name: "Push to NuGet.org"
      run: |
        dotnet nuget push ./artifacts/*.nupkg --skip-duplicate -k ${{ steps.op-load-secret.outputs.NUGET_AUTH_TOKEN }} -s https://api.nuget.org/v3/index.json
