name: Build-Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    if: "contains(github.ref, 'refs/tags')"

    # To build `net45` target, we need to run the build on Windows.
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
    
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: "dotnet build & pack"
      run: |
        dotnet restore
        dotnet build -c Release
        dotnet pack -c Release -o $GITHUB_WORKSPACE/artifacts -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

    - uses: actions/upload-artifact@master
      with:
        name: Packages
        path: artifacts

    - name: "Push to NuGet.org"
      run: |
        dotnet nuget push "$GITHUB_WORKSPACE/artifacts/*.nupkg" --skip-duplicate -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
